# gitprompt shell integration — generated by "gitprompt init bash"
# Linux/macOS — add to ~/.bashrc:  eval "$($HOME/.local/bin/gitprompt init bash)"
# Windows Git Bash — add to ~/.bashrc: eval "$($HOME/.local/bin/gitprompt.exe init bash)"
if [[ "$OSTYPE" == msys || "$OSTYPE" == cygwin ]]; then
  _GITPROMPT_BIN="$HOME/.local/bin/gitprompt.exe"
  _GITPROMPT_FALLBACK_PS1='\w ❯ '
else
  _GITPROMPT_BIN="$HOME/.local/bin/gitprompt"
  _GITPROMPT_FALLBACK_PS1='\w \$ '
fi

gitprompt() {
  case "${1:-} ${2:-}" in
    "aliases enable"|"aliases disable"|"update aliases")
      local _script
      _script="$("$_GITPROMPT_BIN" "$@")"
      [ -n "$_script" ] && eval "$_script"
      ;;
    *)
      "$_GITPROMPT_BIN" "$@"
      ;;
  esac
}

if [ -z "${_GITPROMPT_ORIGINAL_PS1+x}" ]; then
  _GITPROMPT_ORIGINAL_PS1="$PS1"
fi

_GITPROMPT_PROMPT_START_OF_LINE={{GITPROMPT_PROMPT_START_OF_LINE}}

if [ -z "${__gitprompt_cmd_start_us+x}" ]; then
  __gitprompt_preexec_flag=0
  __gitprompt_running=0
  __gitprompt_cmd_start_us=""
fi

__gitprompt_debug_trap() {
  if [ "$__gitprompt_running" -eq 0 ] && [ "$BASH_COMMAND" != "_gitprompt_update_ps1" ]; then
    if [ "$__gitprompt_preexec_flag" -eq 0 ] && [ -n "${EPOCHREALTIME+x}" ]; then
      __gitprompt_cmd_start_us=${EPOCHREALTIME/./}
    fi
    __gitprompt_preexec_flag=1
  fi
}

__gitprompt_prompt_sp() {
  [ -t 1 ] || return
  local pos _d _saved_stty
  _saved_stty=$(stty -g 2>/dev/null) || return
  # Each `read -s` only disables echo for its own call, then restores it —
  # leaving gaps (between the drain loop, the query, and the reply read)
  # where echo is back on. If the terminal's reply lands in one of those
  # gaps, the kernel echoes the raw bytes to the screen right then, even
  # though the read afterward still consumes them fine — that's what shows
  # up as literal "^[[row;colR" text. Holding echo off for the whole probe
  # closes those gaps.
  stty -echo -icanon 2>/dev/null
  while IFS= read -d R -rs -t 0.02 _d 2>/dev/null; do :; done
  printf '\e[6n' >&1
  if ! IFS='[;' read -d R -a pos -rs -t 0.3 2>/dev/null; then
    while IFS= read -d R -rs -t 0.2 _d 2>/dev/null; do :; done
    stty "$_saved_stty" 2>/dev/null
    return
  fi
  stty "$_saved_stty" 2>/dev/null
  local col="${pos[2]:-1}"
  [ "${col}" -gt 1 ] && printf '\n'
}

_gitprompt_update_ps1() {
  __gitprompt_running=1
  local _last_cmd_ms=""
  if [ -n "$__gitprompt_cmd_start_us" ]; then
    local _end_us=${EPOCHREALTIME/./}
    _last_cmd_ms=$(( (_end_us - __gitprompt_cmd_start_us) / 1000 ))
    __gitprompt_cmd_start_us=""
  elif [ -n "${EPOCHREALTIME+x}" ]; then
    _last_cmd_ms="0"
  fi
  [ "${_GITPROMPT_PROMPT_START_OF_LINE:-1}" = "1" ] && __gitprompt_prompt_sp
  if [ "$__gitprompt_preexec_flag" -eq 1 ]; then
    __gitprompt_preexec_flag=0
    "$_GITPROMPT_BIN" --invalidate-status-cache >/dev/null 2>&1 || true
  fi
  if output="$(GITPROMPT_LAST_CMD_MS="$_last_cmd_ms" "$_GITPROMPT_BIN" 2>/dev/null)" && [ -n "$output" ]; then
    PS1="$output"
  else
    PS1="${_GITPROMPT_ORIGINAL_PS1:-$_GITPROMPT_FALLBACK_PS1}"
  fi
  __gitprompt_running=0
}

if [ -x "$_GITPROMPT_BIN" ]; then
  trap '__gitprompt_debug_trap' DEBUG
  if [[ "${PROMPT_COMMAND}" != *_gitprompt_update_ps1* ]]; then
    PROMPT_COMMAND="_gitprompt_update_ps1${PROMPT_COMMAND:+; $PROMPT_COMMAND}"
  fi
fi

_gitprompt_complete() {
  [ "$COMP_CWORD" -eq 0 ] && return
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local prev="${COMP_WORDS[COMP_CWORD-1]}"
  case "$prev" in
    gitprompt|gitprompt.exe) COMPREPLY=($(compgen -W "{{GITPROMPT_COMMANDS}}" -- "$cur")) ;;
    init)                    COMPREPLY=($(compgen -W "bash" -- "$cur")) ;;
    config)                  COMPREPLY=($(compgen -W "reset" -- "$cur")) ;;
    update)                  COMPREPLY=($(compgen -W "aliases" -- "$cur")) ;;
    aliases)                 COMPREPLY=($(compgen -W "enable disable" -- "$cur")) ;;
  esac
}
complete -F _gitprompt_complete gitprompt
[[ "$OSTYPE" == msys || "$OSTYPE" == cygwin ]] && complete -F _gitprompt_complete gitprompt.exe

if ! type __git_complete >/dev/null 2>&1; then
  _gitprompt_f="$HOME/.local/share/gitprompt/git-completion.bash"
  # shellcheck disable=SC1090
  [ -f "$_gitprompt_f" ] && . "$_gitprompt_f"
  unset _gitprompt_f
fi

_gitprompt_aliases="$HOME/.local/share/gitprompt/git_aliases.sh"
# shellcheck disable=SC1090
if [ -f "$_gitprompt_aliases" ]; then
  . "$_gitprompt_aliases"
  _GITPROMPT_ALIASES_ENABLED=1
else
  _GITPROMPT_ALIASES_ENABLED=0
fi
unset _gitprompt_aliases
