namespace GitPrompt.Prompting;

internal static class ShellInitializer
{
    internal static void Initialize(string shell)
    {
        if (!string.Equals(shell, "bash", StringComparison.OrdinalIgnoreCase))
        {
            Console.Error.WriteLine(
                string.IsNullOrEmpty(shell)
                    ? "gitprompt: init requires a shell name"
                    : $"gitprompt: unsupported shell for 'init': '{shell}'");
            Console.Error.WriteLine("Supported shells: bash");
            Console.Error.WriteLine("Usage: eval \"$(gitprompt init bash)\"");
            Environment.Exit(1);
            return;
        }

        var script = GenerateBashInit().ReplaceLineEndings("\n");
        var bytes = Console.OutputEncoding.GetBytes(script);
        using var stdout = Console.OpenStandardOutput();
        stdout.Write(bytes);
    }

    // Returns the Bash integration script. Exposed for testing.
    internal static string GenerateBashInit()
    {
        var fallbackPs1 = OperatingSystem.IsWindows() ? @"\w > " : @"\w \$ ";
        return GenerateBashInit(fallbackPs1);
    }

    // Overload that accepts a custom fallback PS1, used in tests.
    internal static string GenerateBashInit(string fallbackPs1)
    {
        return $$"""
        # gitprompt shell integration — generated by "gitprompt init bash"
        # Add to ~/.bashrc: eval "$(gitprompt init bash)"
        _GITPROMPT_BIN="$(command -v gitprompt 2>/dev/null)"

        __gitprompt_preexec_flag=0
        __gitprompt_running=0

        __gitprompt_debug_trap() {
          if [ "$__gitprompt_running" -eq 0 ] && [ "$BASH_COMMAND" != "_gitprompt_update_ps1" ]; then
            __gitprompt_preexec_flag=1
          fi
        }

        _gitprompt_update_ps1() {
          __gitprompt_running=1
          if [ "$__gitprompt_preexec_flag" -eq 1 ]; then
            __gitprompt_preexec_flag=0
            "$_GITPROMPT_BIN" --invalidate-status-cache >/dev/null 2>&1 || true
          fi
          if output="$("$_GITPROMPT_BIN" 2>/dev/null)" && [ -n "$output" ]; then
            PS1="$output"
          else
            PS1='{{fallbackPs1}}'
          fi
          __gitprompt_running=0
        }

        if [ -x "$_GITPROMPT_BIN" ]; then
          trap '__gitprompt_debug_trap' DEBUG
          PROMPT_COMMAND="_gitprompt_update_ps1${PROMPT_COMMAND:+; $PROMPT_COMMAND}"
        fi

        """;
    }
}
